#!/usr/bin/env bash
username="xavier"
home="/home/$username"
boot_log="$home/boot.log"
old_boot_log="$home/boot.old.log"
{
    # laod the home of the xavier so that python3 is the correct python and PYTHONPATH (and other env vars) are setup
    . "/home/$username/.zshrc"
    
    # # handle logging file
    # rm -f "$old_boot_log"
    # # copy old file
    # if [ -f "$boot_log" ]
    # then
    #     cp "$boot_log" "$old_boot_log"
    # fi
    # rm -f "$boot_log"
    
    echo starting
    . "$home/repos/cv_dark/commands/xavier/boot_control/boot_command.ignore"
    echo process died
    # echo "# "                           >>"$boot_log"
    # echo "# "                           >>"$boot_log"
    # echo "# PROCESS DIED: TRYING AGAIN" >>"$boot_log"
    # echo "# "                           >>"$boot_log"
    # echo "# "                           >>"$boot_log"
    # while true
    # do
    # done
} 2>"$boot_log.err" 1>"$boot_log"