#!/usr/bin/env bash


# 
# note: all this file does is login as the xavier user, cd to the repo, and then run the "xavier/boot_control/boot_command.ignore"
#       this handles logging output to a file

username="xavier"
home="/home/$username"
boot_log="$home/boot.log"
old_boot_log="$home/boot.old.log"

# handle logging file
rm -f "$old_boot_log"
# copy old file
if [ -f "$boot_log" ]
then
    cp "$boot_log" "$old_boot_log"
fi
rm -f "$boot_log"


sudo runuser - "$username" -c '
    while true
    do
        cd /home/xavier/repos/cv_dark/
        . "/home/xavier/repos/cv_dark/commands/xavier/boot_control/boot_command.ignore"
        
        echo "#"
        echo "#"
        echo "#"
        echo "# PROCESS DIED RESTARTING"
        echo "#"
        echo "#"
        echo "#"
    done
'  2>>"$boot_log" 1>>"$boot_log"