#!/usr/bin/env bash
ps aux | grep -v $$ | grep -v grep |  grep -E "cv_dark" | awk '{ print $2 }' | sudo xargs kill -9 2>/dev/null
ps aux | grep -v $$ | grep -v grep |  grep -E "cv_dark" | awk '{ print $2 }' | sudo xargs kill -9 2>/dev/null
ps aux | grep -v $$ | grep -v grep |  grep -E "cv_dark" | awk '{ print $2 }' | sudo xargs kill -9 2>/dev/null